package DanMu.findUsages;

/*Generated by MPS */

import jetbrains.mps.ide.findusages.BaseFindUsagesDescriptor;
import org.jetbrains.mps.openapi.persistence.PersistenceFacade;

public class FindUsagesDescriptor extends BaseFindUsagesDescriptor {
  public FindUsagesDescriptor() {
    super(PersistenceFacade.getInstance().createModuleReference("f308bac3-fb95-4e51-8457-a8a5d4e826ac(DanMu)"), PersistenceFacade.getInstance().createModelReference("r:63c299b3-9931-42f7-a31d-227e5b9eef25(DanMu.findUsages)"));
  }
  public void init() {
  }
}
