package DataModel.structure;

/*Generated by MPS */

import java.util.List;
import jetbrains.mps.internal.collections.runtime.ListSequence;
import java.util.LinkedList;

public enum MoneyType {
  coin("coin", "coin"),
  diamond("diamond", "diamond");

  private final String myName;
  public String getName() {
    return myName;
  }
  private final String myValue;
  private MoneyType(String name, String value) {
    myName = name;
    myValue = value;
  }
  public String getValue() {
    return myValue;
  }
  public String getValueAsString() {
    return myValue;
  }
  public static List<MoneyType> getConstants() {
    List<MoneyType> list = ListSequence.fromList(new LinkedList<MoneyType>());
    ListSequence.fromList(list).addElement(MoneyType.coin);
    ListSequence.fromList(list).addElement(MoneyType.diamond);
    return list;
  }
  public static MoneyType getDefault() {
    return MoneyType.coin;
  }
  public static MoneyType parseValue(String value) {
    if (value == null) {
      return MoneyType.getDefault();
    }
    if (value.equals(MoneyType.coin.getValueAsString())) {
      return MoneyType.coin;
    }
    if (value.equals(MoneyType.diamond.getValueAsString())) {
      return MoneyType.diamond;
    }
    return MoneyType.getDefault();
  }
}
