package DataModel.structure;

/*Generated by MPS */

import jetbrains.mps.smodel.runtime.BaseStructureAspectDescriptor;
import java.util.Map;
import jetbrains.mps.smodel.adapter.ids.SConceptId;
import java.util.HashMap;
import jetbrains.mps.smodel.runtime.ConceptDescriptor;
import java.util.Collection;
import java.util.Arrays;
import org.jetbrains.annotations.Nullable;
import org.jetbrains.mps.openapi.language.SAbstractConcept;
import jetbrains.mps.smodel.adapter.structure.concept.SConceptAdapterById;
import jetbrains.mps.smodel.adapter.structure.concept.SInterfaceConceptAdapterById;
import jetbrains.mps.smodel.runtime.impl.ConceptDescriptorBuilder;
import jetbrains.mps.smodel.adapter.ids.MetaIdFactory;
import jetbrains.mps.smodel.SNodePointer;

public class StructureAspectDescriptor extends BaseStructureAspectDescriptor {
  private final Map<SConceptId, Integer> myIndexMap = new HashMap<SConceptId, Integer>(16);
  /*package*/ final ConceptDescriptor myConceptBoolValue = createDescriptorForBoolValue();
  /*package*/ final ConceptDescriptor myConceptChildString = createDescriptorForChildString();
  /*package*/ final ConceptDescriptor myConceptLuaTF = createDescriptorForLuaTF();
  /*package*/ final ConceptDescriptor myConceptLuaTable = createDescriptorForLuaTable();
  /*package*/ final ConceptDescriptor myConceptLuaTableField = createDescriptorForLuaTableField();
  /*package*/ final ConceptDescriptor myConceptLuaTableReference = createDescriptorForLuaTableReference();
  /*package*/ final ConceptDescriptor myConceptModel = createDescriptorForModel();
  /*package*/ final ConceptDescriptor myConceptNumberReference = createDescriptorForNumberReference();
  /*package*/ final ConceptDescriptor myConceptNumberValue = createDescriptorForNumberValue();
  /*package*/ final ConceptDescriptor myConceptResource = createDescriptorForResource();
  /*package*/ final ConceptDescriptor myConceptResourceItem = createDescriptorForResourceItem();
  /*package*/ final ConceptDescriptor myConceptResourceMoney = createDescriptorForResourceMoney();
  /*package*/ final ConceptDescriptor myConceptStringValue = createDescriptorForStringValue();
  /*package*/ final ConceptDescriptor myConceptValue = createDescriptorForValue();
  /*package*/ final ConceptDescriptor myConceptValueAssignment = createDescriptorForValueAssignment();
  /*package*/ final ConceptDescriptor myConceptValueTransform = createDescriptorForValueTransform();

  public StructureAspectDescriptor() {
    myIndexMap.put(myConceptBoolValue.getId(), 0);
    myIndexMap.put(myConceptChildString.getId(), 1);
    myIndexMap.put(myConceptLuaTF.getId(), 2);
    myIndexMap.put(myConceptLuaTable.getId(), 3);
    myIndexMap.put(myConceptLuaTableField.getId(), 4);
    myIndexMap.put(myConceptLuaTableReference.getId(), 5);
    myIndexMap.put(myConceptModel.getId(), 6);
    myIndexMap.put(myConceptNumberReference.getId(), 7);
    myIndexMap.put(myConceptNumberValue.getId(), 8);
    myIndexMap.put(myConceptResource.getId(), 9);
    myIndexMap.put(myConceptResourceItem.getId(), 10);
    myIndexMap.put(myConceptResourceMoney.getId(), 11);
    myIndexMap.put(myConceptStringValue.getId(), 12);
    myIndexMap.put(myConceptValue.getId(), 13);
    myIndexMap.put(myConceptValueAssignment.getId(), 14);
    myIndexMap.put(myConceptValueTransform.getId(), 15);
  }

  @Override
  public Collection<ConceptDescriptor> getDescriptors() {
    return Arrays.asList(myConceptBoolValue, myConceptChildString, myConceptLuaTF, myConceptLuaTable, myConceptLuaTableField, myConceptLuaTableReference, myConceptModel, myConceptNumberReference, myConceptNumberValue, myConceptResource, myConceptResourceItem, myConceptResourceMoney, myConceptStringValue, myConceptValue, myConceptValueAssignment, myConceptValueTransform);
  }

  @Override
  @Nullable
  public ConceptDescriptor getDescriptor(SConceptId id) {
    Integer index = myIndexMap.get(id);
    if (index == null) {
      return null;
    }
    switch (((int) index)) {
      case 0:
        return myConceptBoolValue;
      case 1:
        return myConceptChildString;
      case 2:
        return myConceptLuaTF;
      case 3:
        return myConceptLuaTable;
      case 4:
        return myConceptLuaTableField;
      case 5:
        return myConceptLuaTableReference;
      case 6:
        return myConceptModel;
      case 7:
        return myConceptNumberReference;
      case 8:
        return myConceptNumberValue;
      case 9:
        return myConceptResource;
      case 10:
        return myConceptResourceItem;
      case 11:
        return myConceptResourceMoney;
      case 12:
        return myConceptStringValue;
      case 13:
        return myConceptValue;
      case 14:
        return myConceptValueAssignment;
      case 15:
        return myConceptValueTransform;
      default:
        throw new IllegalStateException();
    }
  }

  /*package*/ int internalIndex(SAbstractConcept c) {
    Integer res = null;
    if (c instanceof SConceptAdapterById) {
      res = myIndexMap.get(((SConceptAdapterById) c).getId());
    } else if (c instanceof SInterfaceConceptAdapterById) {
      res = myIndexMap.get(((SInterfaceConceptAdapterById) c).getId());
    }
    return (res == null ? -1 : res);
  }

  private static ConceptDescriptor createDescriptorForBoolValue() {
    return new ConceptDescriptorBuilder("DataModel.structure.BoolValue", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eadea6d01L)).super_("DataModel.structure.Value").version(1).super_(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).parents("DataModel.structure.Value").parentIds(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234230529")).create();
  }
  private static ConceptDescriptor createDescriptorForChildString() {
    return new ConceptDescriptorBuilder("DataModel.structure.ChildString", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eecbbbfL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x7c563eb53eecc5c9L, "value", new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8959417456865887689"))).properties("value").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8959417456865885119")).create();
  }
  private static ConceptDescriptor createDescriptorForLuaTF() {
    return new ConceptDescriptorBuilder("DataModel.structure.LuaTF", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x123e4f2456b4f8c5L)).super_("jetbrains.mps.baseLanguage.structure.Expression").version(1).super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x123e4f2456b4f8c6L, "table", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eec164eL), true, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "1314575158730881222")), new ConceptDescriptorBuilder.Ref(0x123e4f2456b4f8c8L, "field", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7cbac5d8e7d43e06L), true, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "1314575158730881224"))).references("table", "field").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "1314575158730881221")).create();
  }
  private static ConceptDescriptor createDescriptorForLuaTable() {
    return new ConceptDescriptorBuilder("DataModel.structure.LuaTable", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eec164eL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x7cbec709645ceee2L, "tableName", new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8988840749430533858"))).properties("tableName").childDescriptors(new ConceptDescriptorBuilder.Link(0x7c563eb53eec1660L, "keys", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eecbbbfL), false, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8959417456865842784")), new ConceptDescriptorBuilder.Link(0x6a9d6b2bd5de761aL, "fields", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7cbac5d8e7d43e06L), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "7682414375379826202"))).children(new String[]{"keys", "fields"}, new boolean[]{true, true}).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8959417456865842766")).create();
  }
  private static ConceptDescriptor createDescriptorForLuaTableField() {
    return new ConceptDescriptorBuilder("DataModel.structure.LuaTableField", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7cbac5d8e7d43e06L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8987713541764300294")).create();
  }
  private static ConceptDescriptor createDescriptorForLuaTableReference() {
    return new ConceptDescriptorBuilder("DataModel.structure.LuaTableReference", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e250666cd08026cL)).super_("jetbrains.mps.baseLanguage.structure.Expression").version(1).super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x7e250666cd08026dL, "table", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eec164eL), false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9089678461513499245"))).references("table").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9089678461513499244")).create();
  }
  private static ConceptDescriptor createDescriptorForModel() {
    return new ConceptDescriptorBuilder("DataModel.structure.Model", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade95480L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept", "jetbrains.mps.lang.core.structure.ScopeProvider").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x33d23ee961a0cbf3L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x771d1e0eade95501L, "values", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234158849")), new ConceptDescriptorBuilder.Link(0x7c563eb53eec3e07L, "tables", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7c563eb53eec164eL), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8959417456865852935")), new ConceptDescriptorBuilder.Link(0x7e59491b2c5c34d9L, "transform", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c5bb032L), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763353305"))).children(new String[]{"values", "tables", "transform"}, new boolean[]{true, true, true}).rootable().sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234158720")).create();
  }
  private static ConceptDescriptor createDescriptorForNumberReference() {
    return new ConceptDescriptorBuilder("DataModel.structure.NumberReference", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c5c3470L)).super_("jetbrains.mps.baseLanguage.structure.Expression").version(1).super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x7e59491b2c5c348cL, "value", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eadea6cebL), false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763353228"))).references("value").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763353200")).create();
  }
  private static ConceptDescriptor createDescriptorForNumberValue() {
    return new ConceptDescriptorBuilder("DataModel.structure.NumberValue", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eadea6cebL)).super_("DataModel.structure.Value").version(1).super_(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).parents("DataModel.structure.Value").parentIds(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234230507")).create();
  }
  private static ConceptDescriptor createDescriptorForResource() {
    return new ConceptDescriptorBuilder("DataModel.structure.Resource", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL)).super_("jetbrains.mps.baseLanguage.structure.Expression").version(1).super_(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).parents("jetbrains.mps.baseLanguage.structure.Expression").parentIds(MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL)).childDescriptors(new ConceptDescriptorBuilder.Link(0x7e59491b2c62329fL, "num", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763745951"))).children(new String[]{"num"}, new boolean[]{false}).abstract_().sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763737084")).create();
  }
  private static ConceptDescriptor createDescriptorForResourceItem() {
    return new ConceptDescriptorBuilder("DataModel.structure.ResourceItem", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c6232afL)).super_("DataModel.structure.Resource").version(1).super_(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL)).parents("DataModel.structure.Resource").parentIds(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x7e59491b2c6232b0L, "id", new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763745968"))).properties("id").alias("item", "").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763745967")).create();
  }
  private static ConceptDescriptor createDescriptorForResourceMoney() {
    return new ConceptDescriptorBuilder("DataModel.structure.ResourceMoney", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c621007L)).super_("DataModel.structure.Resource").version(1).super_(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL)).parents("DataModel.structure.Resource").parentIds(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL)).propertyDescriptors(new ConceptDescriptorBuilder.Prop(0x7e59491b2c621a96L, "type", new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763739798"))).properties("type").alias("money", "").sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763737095")).create();
  }
  private static ConceptDescriptor createDescriptorForStringValue() {
    return new ConceptDescriptorBuilder("DataModel.structure.StringValue", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eadea6cd9L)).super_("DataModel.structure.Value").version(1).super_(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).parents("DataModel.structure.Value").parentIds(MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234230489")).create();
  }
  private static ConceptDescriptor createDescriptorForValue() {
    return new ConceptDescriptorBuilder("DataModel.structure.Value", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).abstract_().sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "8583049513234158941")).create();
  }
  private static ConceptDescriptor createDescriptorForValueAssignment() {
    return new ConceptDescriptorBuilder("DataModel.structure.ValueAssignment", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c62ae88L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).referenceDescriptors(new ConceptDescriptorBuilder.Ref(0x7e59491b2c62aea7L, "value", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x771d1e0eade9555dL), false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763777703"))).references("value").childDescriptors(new ConceptDescriptorBuilder.Link(0x7e59491b2c62ae8cL, "expression", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), false, false, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763777676"))).children(new String[]{"expression"}, new boolean[]{false}).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763777672")).create();
  }
  private static ConceptDescriptor createDescriptorForValueTransform() {
    return new ConceptDescriptorBuilder("DataModel.structure.ValueTransform", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c5bb032L)).super_("jetbrains.mps.lang.core.structure.BaseConcept").version(1).super_(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL)).parents("jetbrains.mps.lang.core.structure.BaseConcept", "jetbrains.mps.lang.core.structure.INamedConcept").parentIds(MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x10802efe25aL), MetaIdFactory.conceptId(0xceab519525ea4f22L, 0x9b92103b95ca8c0cL, 0x110396eaaa4L)).childDescriptors(new ConceptDescriptorBuilder.Link(0x7e59491b2c5c34d4L, "check", MetaIdFactory.conceptId(0xf3061a5392264cc5L, 0xa443f952ceaf5816L, 0xf8c37f506fL), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763353300")), new ConceptDescriptorBuilder.Link(0x7e59491b2c6243b8L, "cost", MetaIdFactory.conceptId(0xa61bdb2ea7448deL, 0x85237d716d56eee2L, 0x7e59491b2c620ffcL), true, true, false, new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763750328"))).children(new String[]{"check", "cost"}, new boolean[]{true, true}).sourceNode(new SNodePointer("r:4a1e5cde-b36a-48af-8ad2-ac08d32e032f(DataModel.structure)", "9104388502763319346")).create();
  }
}
